#version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

      #zookeeper:
    #image: wurstmeister/zookeeper:3.4.6
    #ports:
    # - "2181:2181"

        #  zookeeper:
        #image: zookeeper
        #restart: always
        #hostname: zoo1
        #ports:
        #- 2181:2181
    #environment:
    #ZOO_MY_ID: 1
    #ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181    

#   kafka:
#     image: wurstmeister/kafka:latest
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#     depends_on:
#       - zookeeper
# 
  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"
    volumes:
      - namenode:/hadoop/dfs/name

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - datanode:/hadoop/dfs/data
    depends_on:
      - hdfs-namenode

#   hive:
#     image: bde2020/hive:2.3.2-postgresql-metastore
#     ports:
#       - "10000:10000"
#       - "10002:10002"
#     environment:
#       - HIVE_METASTORE_URI=thrift://hive-metastore:9083
#       - HIVE_META_STORE_HOST=hive-metastore
#       - SERVICE_PRECONDITION=hive-metastore:9083
#     depends_on:
#       - hdfs-namenode
#       - hdfs-datanode
#       - hive-metastore
# 
#   hive-metastore:
#     image: bde2020/hive-metastore-postgresql:2.3.0
#     environment:
#       - POSTGRES_HOST=postgres
#       - POSTGRES_PORT=5432
#       - POSTGRES_DB=metastore
#       - POSTGRES_USER=airflow
#       - POSTGRES_PASSWORD=airflow
#     ports:
#       - "9083:9083"
#     depends_on:
#       - postgres
# 
  airflow:
    image: puckel/docker-airflow:latest
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: mQOFQEyfC28IP5ipi--PJF1f1UHVEqwIL8keubsg3R0=
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: hdfs://172.20.104.17:9870/user/airflow/logs
    ports:
      - "8080:8080"
    volumes:
      - /mnt/c/Users/cgsilveriot/Engineer/MicroDataLake/Dags:/usr/local/airflow/dags    
    depends_on:
      - postgres
    network_mode: "host"

  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_NAME=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "8081:8081"
    volumes:
      - spark-data:/bitnami/spark

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark
    volumes:
      - spark-worker-data:/bitnami/spark

volumes:
  namenode:
  datanode:
  spark-data:
  spark-worker-data:



