#version: '3.7'
# version estable
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  airflow:
    image: puckel/docker-airflow:latest
    user: root
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: mQOFQEyfC28IP5ipi--PJF1f1UHVEqwIL8keubsg3R0=
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    ports:
      - "8080:8080"
    volumes:
      - /c/Users/cgsilveriot/Engineer/MicroDataLake/Dags/dev/:/usr/local/airflow/dags
      - airflow_config:/usr/local/airflow
      - airflow_lib:/usr/local/lib
    depends_on:
      - postgres
    networks:
      - airflow_network

  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"
    volumes:
      - namenode_data:/hadoop/dfs/name
    networks:
      - airflow_network

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - hdfs-namenode
    #volumes:
     # - namenode_data:/hadoop/dfs/data
    networks:
      - airflow_network

networks:
  airflow_network:
    driver: bridge

volumes:
  airflow_config:
  airflow_lib:
  namenode_data:
  #datanode_data:
  postgres_data: