#version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
 
  airflow:
    image: puckel/docker-airflow:latest
    #image: custom-airflow:latest
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@localhost:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: mQOFQEyfC28IP5ipi--PJF1f1UHVEqwIL8keubsg3R0=
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: hdfs://172.20.104.17:9870/user/airflow/logs
    ports:
      - "8080:8080"
    volumes:
      - /mnt/c/Users/cgsilveriot/Engineer/MicroDataLake/Dags:/usr/local/airflow/dags    
    depends_on:
      - postgres
    networks:
      - airflow_network

networks:
  airflow_network:
    external: true
